### ISSUE TITLE
Geometries are different!!

### ISSUE THREAD

**Issue by dnavarrocueto** [nextgis/molusce#10]
Hi all.

I'm trying to use molusce but I'm getting some troubles. When I add spatial variables and click 'check geometry' I got a message which said that geometries of the initial raster and the one used as spatial variable are different.

How can I fix it?

Thanks.

**Comment by dnavarrocueto** [comment]
Thank you! It works for me.

**Comment by dnavarrocueto** [comment]
I've got another problem. The land use raster I am using is too big. When I clip it and click on 'update tables' in the 'area changes' tab I get the following error.

ValueError: operands could not be broadcast together with shapes (30) (29)

**Comment by NGANROS** [comment]
I HAVE SAME PROBLEM ABOVE IN USE MOLUSCE

**Comment by hafez-ahmad** [comment]
in qgis3.01
This plugin is broken
Error reading metadata: general

**Comment by Astori68** [comment]
Hello. I am using MOLUSCE for forecasting LULC, using 1980 and 1990 landcover and slope as spatial variable but the output prediction is same as the final. Kindly guide me what should I do?

**Comment by itssalim** [comment]
Kindly update the plugin for QGIS 3.X. The plugin is not available in QGIS 3.X

**Comment by MPEPENAL** [comment]
Muy buen complento, estaria bueno una actualizacion para QGIS3.x

**Comment by MPEPENAL** [comment]
> Hola. Estoy usando MOLUSCE para pronosticar LULC, usando la cobertura del suelo y la pendiente de 1980 y 1990 como variable espacial, pero la predicción de salida es la misma que la final. Guíeme amablemente, ¿qué debo hacer?

Que modelo estas usando?

**Comment by palarifeen** [comment]
I have prepared my initial map, final map and all variables in same geometry. But, simulated geometry is different and this is why I could not validate map with reference map.How can I solve the problem?

**Comment by MPEPENAL** [comment]
> He preparado mi mapa inicial, mapa final y todas las variables en la misma geometría. Pero la geometría simulada es diferente y es por eso que no pude validar el mapa con el mapa de referencia ¿Cómo puedo resolver el problema



> Preparó mi mapa inicial, mapa final y todas las variables en la misma geometría. Pero la geometría simulada es diferente y es por eso que no pude validar el mapa con el mapa de referencia ¿Cómo puedo resolver el problema?

CAMBIA LA GEOMETRIA DEL MAPA SIMULADO EN QGIS.
