### ISSUE TITLE
Prevent simulation if raster geometries do not match

### ISSUE THREAD

**Issue by marisn** [nextgis/molusce#19]
Even when "check geometry" fails, it allows to proceed. Still when trying to run the simulation, it is crashing. As simulation part can not be performed if geometries do not match, the module should not allow to start simulation unless check passes.

**Comment by simgislab** [comment]
@KolesovDmitry have a look may be when time permits?

**Comment by imaikop444** [comment]
Good morning everyone.

I love this plugin, please can someone help me and send the plugin to me via this mail pauludongimakop@gmail.com.
I download the plugin online but it didn't work because there's is no installation file in it.
[Uploading molusce-3.0.13 (1).zip…]()

**Comment by imaikop444** [comment]
Please am in urgent need of it. I am using QGIS 2.0.1 Dufour. i want to use for prediction.
