### ISSUE TITLE
Results in Transition Potential Modelling

### ISSUE THREAD

**Issue by juda-garcia** [nextgis/molusce#25]
how interpret the results in the transition potential modelling? how to know the confidence intervals? in the technical information methods and algorithms does no
![transition](https://user-images.githubusercontent.com/34290080/35939345-7417f5cc-0c11-11e8-8c25-9baec572b94e.PNG)
t appear

**Comment by simgislab** [comment]
may be this will be of help http://wiki.gis-lab.info/w/Landscape_change_analysis_with_MOLUSCE_-_methods_and_algorithms#Logistic_regression

**Comment by KolesovDmitry** [comment]
Short answer
==========
Unfortunately MOLUSCE doesn't provide confidence intervals. The results on your screenshot are taken by classic multinomial logistic regression. The MOLUSCE implementation of it is here: https://github.com/nextgis/molusce/blob/master/algorithms/models/lr/multinomial_logistic_regression.py

Long Answer
==========
A pdf user-guide is provider with the plugin (see 'About' menu). More techical details are provided here: http://wiki.gis-lab.info/w/Landscape_change_analysis_with_MOLUSCE_-_methods_and_algorithms 

MOLUSCE implements a lot of methods (they are different for different stages of analysis). Bellow are provided some references. The references are examples, you can prefer other authors ;)  

### Change Detection Stage

Methods: post-classification change detection - Singh 1989
Output: 
  - land use and forest cover change matrix
  - land use and forest cover change maps                      

### Modelling transition potential or areas at risk of deforestation 

Input data: 
  - land use and forest cover change maps (e.g., 2000-2010);
  - biophysical datasets e.g., distance to roads, slope etc.
  - socio-economic data e.g., population density, crop production

Methods: 
  - artificial neural networks (ANN) - Pijanowski et al. 2002 and 2005. 
  - weights of evidence (WoE) - Bonham-Carter et al. 1988; Almeida et al., 2005.
  - multi-criteria evaluation (MCE) - Wu and Webster 1998; Eastman et al 2005.
  - logistic regression - Eastman et al. 2005; Mertens and Lambin 1997.

Output: deforestation risk maps


### Simulating future land use and forest cover changes

Input data: 
  - base land use and forest cover map (e.g. 2000) 
  - transition potential or deforestation risk maps

Methods:  
  - cellular automata model - Wolfram 1984; Wu and Webster 1998.
  - validation (quantity) using Kappa statistics - Pontius et al 2004.       

Output: simulated future land use and forest cover changes

**Comment by juda-garcia** [comment]
@simgislab  @KolesovDmitry  Thank you. I'm going to check that link and bibliography. Can i translate your quick_help.pdf to spanish for Latin America users?

**Comment by simgislab** [comment]
sure, send the translation our way too when it's done
